---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dep-admin
  namespace: default
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: pod-reader
rules:
- apiGroups: ["*"] 
  resources: ["*"]
  verbs: ["*"]
---  
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: dep-admin-role
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pod-reader
subjects:
- kind: ServiceAccount
  name: dep-admin
  namespace: default
---
apiVersion: v1
kind: Service
metadata:
  name: xxe-service
spec:
  selector:
    app: xxe
  ports:
  - protocol: TCP
    port: 5000
    nodePort: 32345
  type: NodePort
---    
apiVersion: apps/v1
kind: Deployment
metadata:
  name: xxe-deployment
spec:
  selector:
    matchLabels:
      app: xxe
  template:
    metadata:
      name: xxe-app
      labels:
        app: xxe
    spec:
      serviceAccountName: dep-admin
      # automountServiceAccountToken: false
      containers:
      - name: xxe
        image: sharathwe45/xxe-app:latest
        ports:
          - containerPort: 5000     